image: cirrusci/flutter


stages:
  - coverage
  - deploy

code_analyze:
  tags:
    - docker
  stage: coverage
  script:
    - flutter pub get
    - flutter analyze
    - flutter format lib/ test/ --set-exit-if-changed

coverage:
  tags:
    - docker
  stage: coverage
  script:
    - flutter pub get
    - flutter test
