name: future_loading_dialog
description: Easy to use adaptive loading dialog to visualize a Dart Future.
version: 0.2.4
homepage: https://famedly.com
repository: https://gitlab.com/KrilleFear/future_loading_dialog

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
