name: future_loading_dialog
description: Easy to use adaptive loading dialog to visualize a Dart Future.
version: 0.3.0
homepage: https://famedly.com
repository: https://github.com/krille-chan/future-loading-dialog
issues: https://github.com/krille-chan/future-loading-dialog/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  async: ^2.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
